<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-24T17:51:03 IST" name="Default suite" finished-at="2025-07-24T17:51:18 IST" duration-ms="14905">
    <groups>
    </groups>
    <test started-at="2025-07-24T17:51:03 IST" name="Default test" finished-at="2025-07-24T17:51:18 IST" duration-ms="14905">
      <class name="com.onsite.credit_note_test_page.CreditNoteCreateTest">
        <test-method is-config="true" signature="generateTokenForSuite()[pri:0, instance:com.onsite.credit_note_test_page.CreditNoteCreateTest@3bb9a3ff]" started-at="2025-07-24T17:50:54 IST" name="generateTokenForSuite" finished-at="2025-07-24T17:51:03 IST" duration-ms="8270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateTokenForSuite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.onsite.credit_note_test_page.CreditNoteCreateTest@3bb9a3ff]" started-at="2025-07-24T17:51:03 IST" name="setUp" finished-at="2025-07-24T17:51:06 IST" duration-ms="3380" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="postCreditNote()[pri:1, instance:com.onsite.credit_note_test_page.CreditNoteCreateTest@3bb9a3ff]" started-at="2025-07-24T17:51:06 IST" name="postCreditNote" finished-at="2025-07-24T17:51:13 IST" duration-ms="6511" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCreditNote -->
        <test-method signature="getCreditNote()[pri:2, instance:com.onsite.credit_note_test_page.CreditNoteCreateTest@3bb9a3ff]" started-at="2025-07-24T17:51:13 IST" name="getCreditNote" finished-at="2025-07-24T17:51:18 IST" depends-on-methods="com.onsite.credit_note_test_page.CreditNoteCreateTest.postCreditNote" duration-ms="4937" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[JSON schema validation failed: com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: object has missing required properties (["amount"])
    level: "error"
    schema: {"loadingURI":"#","pointer":""}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "required"
    required: ["amount","company_id","creator","id","invoice_date","party_company_user_id","project_id"]
    missing: ["amount"]
---  END MESSAGES  ---
 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: JSON schema validation failed: com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: object has missing required properties (["amount"])
    level: "error"
    schema: {"loadingURI":"#","pointer":""}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "required"
    required: ["amount","company_id","creator","id","invoice_date","party_company_user_id","project_id"]
    missing: ["amount"]
---  END MESSAGES  ---
 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.onsite.utilities_page.SchemaValidator.validateSchema(SchemaValidator.java:32)
at com.onsite.credit_note_test_page.CreditNoteCreateTest.getCreditNote(CreditNoteCreateTest.java:116)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCreditNote -->
      </class> <!-- com.onsite.credit_note_test_page.CreditNoteCreateTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
